[package]
name = "algorithms"
version = "0.2.1"
authors = ["VitalyR <vitalyankh@gmail.com>"]
edition = "2018"
license = "MIT"
documentation=""
description = "A library for most common algorithms"

[dependencies]
